import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";
import { cn } from "@/lib/utils";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          "antialiased",
          "[background-size:20px_20px]",
          "[background-image:radial-gradient(#ede6e6_1px,transparent_1px)]",
          "dark:[background-image:radial-gradient(#2d2d2d_1px,transparent_1px)]"
        )}
      >
        <ThemeProvider
          attribute={"class"}
          enableSystem={true}
          defaultTheme="system"
        >
          <div className="">
            <Navbar />
          </div>
          {children}
          <div>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
